#!/bin/sh
#export http_proxy=http://localhost:3128

alias random-anime='random-entry /data/video/anime'
alias random-music="random-entry /data/music/*"

export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

# Shuttlerock stuff.
#export USE_MEMCACHE=1

# S3.
#export AWS_ACCESS_KEY_ID="YOUR S3 KEY"
#export AWS_SECRET_ACCESS_KEY="YOUR S3 SECRET"
#export FOG_PROVIDER=AWS

# Transloadit.
export TRANSLOADIT_KEY="TRANSLOADIT KEY"
export TRANSLOADIT_SECRET="TRANSLOADIT SECRET"
export TRANSLOADIT_BOARD_ITEM_TEMPLATE=2d220f39d34a4bedaa1b52361be8bd1f
export TRANSLOADIT_BOARD_COVER_TEMPLATE=3a3ffbc211964863a66cd65ed5c05574
export TRANSLOADIT_MOBILE_BACKGROUND_TEMPLATE=e401d10a957a09d651a0173e59027795
export TRANSLOADIT_ORGANISATION_THUMB_TEMPLATE=2c62e91ab04781f4e4208f62e3c0ca85

# Stats debugging
export DEBUG_MIXPANEL=true

# Read-only mode.
export READ_ONLY_MODE=false
